# Generated by Django 5.0.1 on 2024-01-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_title", models.CharField(blank=True, max_length=120, null=True)),
                ("title", models.CharField(blank=True, max_length=120, null=True)),
                ("image", models.ImageField(upload_to="banner-images/")),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
            },
        ),
    ]
