# Generated by Django 5.0.1 on 2024-02-01 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_banner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banner",
            name="sub_title",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="title",
        ),
        migrations.AddField(
            model_name="banner",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="banner",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.product",
            ),
        ),
    ]
