# Generated by Django 5.0.1 on 2024-02-01 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_remove_banner_sub_title_remove_banner_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="product",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="web.product"
            ),
            preserve_default=False,
        ),
    ]
