# Generated by Django 5.0.1 on 2024-02-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_alter_banner_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[("mobile", "Mobile"), ("system", "System")],
                default="system",
                max_length=128,
                null=True,
            ),
        ),
    ]
