# Generated by Django 4.2.9 on 2024-04-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_product_canonical_url_product_key_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='schema_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
