# Generated by Django 4.2.9 on 2024-09-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_product_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='canonical',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='keyword',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
