# Generated by Django 4.2.9 on 2024-09-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_blog_canonical_blog_keyword_blog_meta_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='meta_title',
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
