# Generated by Django 4.2.9 on 2024-09-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_blog_meta_title_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
