# Generated by Django 4.2.9 on 2024-10-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_blog_meta_title_alter_blog_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
    ]
