# Generated by Django 5.0.1 on 2025-04-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='IframeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(help_text='Enter the link to embed in iframe')),
            ],
        ),
    ]
