# Generated by Django 5.0.1 on 2025-04-11 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_iframelink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iframelink',
            options={'verbose_name': 'Iframe Link', 'verbose_name_plural': 'Iframe Link'},
        ),
    ]
