# Generated by Django 5.0.1 on 2025-04-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_iframelink_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iframelink',
            name='link',
            field=models.TextField(help_text='Paste the full iframe embed link or long URL here'),
        ),
    ]
