# Generated by Django 5.0.1 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0018_productcategory_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
