# Generated by Django 5.0.1 on 2026-08-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0019_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="productenquiry",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
