# Generated by Django 5.0.1 on 2026-08-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0020_productenquiry_timestamp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={
                "ordering": ["id"],
                "verbose_name": "Product Category",
                "verbose_name_plural": "Product Categories",
            },
        ),
    ]
