# Generated by Django 5.0.1 on 2026-08-12 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0020_product_is_active"),
        ("web", "0021_alter_productcategory_options"),
    ]

    operations = []
