# Generated by Django 5.0.1 on 2026-08-12

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0022_merge_20260812_1126"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product-categories/"),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="description",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
