# Generated by Django 5.0.1 on 2026-09-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0023_productcategory_image_productcategory_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("home", "Home Page"),
                            ("about", "About Us Page"),
                            ("products", "Products Page"),
                            ("blog", "Blog List Page"),
                            ("contact", "Contact Page"),
                            ("product_detail", "Product Detail (Default)"),
                            ("blog_detail", "Blog Detail (Default)"),
                        ],
                        help_text="Select the page to configure meta tags for.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                (
                    "keywords",
                    models.TextField(
                        blank=True, help_text="Comma-separated keywords", null=True
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("schema_description", models.TextField(blank=True, null=True)),
                ("og_title", models.CharField(blank=True, max_length=255, null=True)),
                ("og_description", models.TextField(blank=True, null=True)),
                (
                    "og_image",
                    models.ImageField(blank=True, null=True, upload_to="meta-tags/"),
                ),
            ],
            options={
                "verbose_name": "Meta Tag",
                "verbose_name_plural": "Meta Tags",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-id"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
