# Generated by Django 5.0.1 on 2026-09-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0024_metatag_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metatag",
            name="page",
            field=models.CharField(
                choices=[
                    ("home", "Home Page"),
                    ("about", "About Us Page"),
                    ("products", "Products Page"),
                    ("blog", "Blog List Page"),
                    ("contact", "Contact Page"),
                ],
                help_text="Select the page to configure meta tags for.",
                max_length=50,
                unique=True,
            ),
        ),
    ]
